# Generated by Django 5.0.3 on 2024-04-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_authdata_delete_userprofile_alter_answer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='title',
            new_name='topic_info',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='points',
            new_name='coin',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_false_1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer_false_2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer_false_3',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer_true',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_question_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_save_topic',
            field=models.IntegerField(default=0),
        ),
    ]
