# Generated by Django 5.0.3 on 2024-04-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_title_topic_topic_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skin',
            field=models.CharField(default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='skin_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='skin_g',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='skin_p',
            field=models.BooleanField(default=False),
        ),
    ]
