# Generated by Django 5.0.3 on 2024-04-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_skin_user_skin_b_user_skin_g_user_skin_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skin',
            field=models.CharField(default='blue', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='skin_b',
            field=models.BooleanField(default=True),
        ),
    ]
